name: Build and deploy Node.js app to Azure Web App - kpi-form
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read  
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
 
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3E946929-F840-438E-A362-1809276C2AFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4E99B5FF-DD77-418A-8B69-1D684E911168 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DB81AC16-6566-4A76-96D7-0C5762742DB1 }}
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kpi-codir'
          slot-name: 'Production'
          package: .
 
          


